import "./globals.css";
import { Dosis } from "next/font/google";
import MainLayout from "@/components/MainLayout";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata = {
  title: "meta.diária app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dosis.className} bg-primary-dark-color  text-center h-full`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
