import Logo from "@/components/Logo";
import "./globals.css";
import { Dosis } from "next/font/google";
import Button from "@/components/Button";
import Menu from "@/components/Menu";

// const inter = Inter({ subsets: ["latin"] });
const dosis = Dosis({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dosis.className} bg-primary-dark-color  text-center h-full`}
      >
        <div className="flex flex-col justify-between h-full px-[60px] py-[50px]">
          <Logo />
          {children}
          <Button>novo hábito</Button>
        </div>
        <Menu />
      </body>
    </html>
  );
}
